version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/TrafficLightsEnhancement/UI"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directories:
      - "/TrafficLightsEnhancement.Tests"
      - "/TrafficLightsEnhancement.Ecs.Tests"
      - "/TrafficLightsEnhancement.Serialization.Tests"
    schedule:
      interval: "weekly"
